### PR TITLE
creation of NuGet package

### LINKED ISSUE #13: Create a nuget package

### PR DESCRIPTION
**Pull request by thoemmi**
With this PR, calling `build.bat all` will also create a NuGet package in the `target\$(configuration)` folder.

If you want to automate the upload to the NuGet gallery, you can [instruct AppVeyor to do so](https://www.appveyor.com/docs/deployment/nuget).

This also fixes #13.

### CODE REVIEW

**Comment by dblock** [comment]
Yes, this is awesome! Haven't been actively developing this - @thoemmi would you like to help out and publish to NuGet/automate it? Let us know what you need. @icnocop was the last person to be doing work here too, cc-ed.

**Comment by thoemmi** [comment]
I'd be glad to help out. However, I would be the owner of the package in the NuGet gallery. Are you fine with that?

**Comment by dblock** [comment]
@thoemmi Totally, I assume you can add other owners? Include me and @icnocop. I'll add you as a collaborator of this repo too, we need more maintainers.

**Comment by dblock** [comment]
@thoemmi I added you as a collaborator of this repo, but please do continue making pull requests for your changes. And feel free to help out with whatever time you have! Glad more people are using this library.

**Comment by thoemmi** [comment]
I just checked the [nuspec](http://docs.nuget.org/Create/NuSpec-Reference) specification: both multiple authors and owners are possible. I'll create another PR for the updated nuspec file tomorrow.

Thanks for making me a collaborator. I hope I can contribute one or another helpful change. Of course I won't commit to the repository directly but via PRs.

**Comment by icnocop** [comment]
Since we're using appveyor for automated CI, I would expect the CI build to automatically push the nuget package to nuget. Depending on how the appveyor CI project (https://ci.appveyor.com/project/dblock/resourcelib) is configured, it may require updates to appveyor.yml. But I don't expect the nuget API key to be exposed in appveyor.yml because that's checked into the repository. So since the owner of the appveyor CI project is @dblock, I would think he would have to update the appveyor CI project as follows:
1. Add the nuget package as an artifact in the Artifacts tab. For example:
Path to artifact : \*.nupkg
Deployment name: **NuGet**
Type: Auto
2. Add the nuget deployment provider in the Deployment tab
API key: \*\*\*\*\*\*
Artifacts: **NuGet**
3. NuGet tab:
Check-mark "Do not publish NuGet package artifacts to account/project feeds on Pull Requests"

**Comment by thoemmi** [comment]
When you add publishing NuGet packages in AppVeyor, you can encrypt the NuGet API key in `appveyor.yml`. See the example at https://www.appveyor.com/docs/deployment/nuget:
```
deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: m49OJ7+Jdt9an3jPcTukHA==
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
```

AppVeyor even hosts a [page](https://ci.appveyor.com/tools/encrypt) where you can encrypt your key. It can then be committed to the public repository securely.

Unfortunately, there's not much doumentation about it. I **guess** the encryption must be done by the account owning the CI build.

**Comment by thoemmi** [comment]
But before starting to publish CI builds to NuGet gallery, maybe we should consider using [semantic versioning](http://semver.org/) to distinguish beta builds from official releases. As far as I see resourcelib uses the MSBuild Version Task to generate dynamic version info. However, I'd suggest to switch to [GitVersion](https://github.com/GitTools/GitVersion). Comments?

**Comment by dblock** [comment]
I agree wrt semantic versioning. LMK what I need/can do wrt keys once you guys sorted it out. I am here to help.

**Pull request merged**
