### PR TITLE
Added .NET 4.5 console application as binary

### PR DESCRIPTION
**Pull request by thoemmi**
This pull request is a follow up of #25. The original PR by @FantasticFiasco said:

> Added console application built with .NET 4.5 that is used in binary
unit tests. It will prove a bug in ResourceLib where unit tests will
succeed on atl.dll but fail on ConsoleApplication_NET4.5.exe.

So far I fixed the failing `VersionResourceTests`. There have been two reasons:

1. Wrong language of the version info resources. The version info in `atl.dll` uses the English locale (1033, en-US), but the new managed assemblies are using the neutral one (0). I changed the tests to respect the actual locale of the DLL.
2. The managed assemblies have a different order of the version info. `atl.dll` has first `StringFileInfo` and then `VarFileInfo`, but in the managed DLLs the order is swapped. I had to replace the `Dictionary<string, ResourceTableHeader>` in `VersionResource` with a `OrderedDictionary` (which unfortunately isn't generic).

This PR is still work in progress, as there are more tests failing.

### CODE REVIEW

**Comment by dblock** [comment]
There's what looks like a legit build failure, otherwise looks good.

**Comment by thoemmi** [comment]
No, `ResourceTests.TestReadWriteResourceBytes` fails for the `ClassLibrary_*` DLLs, both on my machine and AppVeyor. I can fix them by adding padding in `StringTableEntry.Write`, but then the tests fails for all other DLLs. I have to find a way to determine the padding to apply it when applicable.

**Comment by dblock** [comment]
Just to be clear, the failure shows a bug, tack a comment here when the build passes (don't get notifications from github on additional commits/forced pushes).

**Comment by thoemmi** [comment]
@dblock 
I had to change `ResourceTests.TestReadWriteResourceBytes` to ignore .NET assemblies (more precisely, to ignore filenames starting with `ClassLibrary_NET`). Those files use non-standard padding in their `StringTableEntry` resources, thus the byte compare fails. Because I don't know a better solution I decided to ignore them in this specific test. All other tests are green, and I guess this PR can be merged now.

**Comment by dblock** [comment]
Merged, thank you.

**Pull request merged**
