### PR TITLE
Added .NET 4.5 console application as binary (Issue #22)

### PR DESCRIPTION
**Pull request by FantasticFiasco**
Added console application built with .NET 4.5 that is used in binary
unit tests. It will prove a bug in ResourceLib where unit tests will
succeed on atl.dll but fail on ConsoleApplication_NET4.5.exe.

### CODE REVIEW

**Comment by thoemmi** [comment]
@FantasticFiasco could you please check the current sources? Some more x64 issues have been fixed recently, which occured only in .NET 4.5.

**Comment by FantasticFiasco** [comment]
Sorry but no. Don't get me wrong, I understand the purpose of open source, I'm a active contributor and collaborator to other GitHub projects, but this maintainer really rubbed me the wrong way. His lack of commitment to the project pushed me into looking for alternative solutions to my problem, and it didn't take many minutes to find a suitable one using Mono.Cecil.

I think you can be obnoxious and get away with it if what you are creating is truly remarkable. Obviously this isn't the case here.

**Comment by dblock** [comment]
@thoemmi thanks for digging this up and commenting

@fantasticfiasco thanks for your two cents

**Comment by thoemmi** [comment]
I'll continue @FantasticFiasco's work a the new PR #33 .

**Pull request closed without merging**
